"""Prevent duplicate daily assignments

Revision ID: 67faa6f11eff
Revises: f702001ca5fe
Create Date: 2026-09-16 17:53:44.439349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67faa6f11eff'
down_revision = 'f702001ca5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_duty_assignment_soldier_date', ['soldier_id', 'duty_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_duty_assignment_soldier_date', type_='unique')

    # ### end Alembic commands ###
