"""Initial schema

Revision ID: f702001ca5fe
Revises: 
Create Date: 2026-09-16 17:07:52.380612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f702001ca5fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_date')
    )
    op.create_table('duty_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('shifts_per_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('soldier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('military_id', sa.String(length=20), nullable=False),
    sa.Column('enlistment_date', sa.Date(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('exemption_no_duty', sa.Boolean(), nullable=True),
    sa.Column('exemption_no_shaving', sa.Boolean(), nullable=True),
    sa.Column('exemption_no_boots', sa.Boolean(), nullable=True),
    sa.Column('days_out_of_service', sa.Integer(), nullable=True),
    sa.Column('out_of_service_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('mother_profession', sa.String(length=100), nullable=True),
    sa.Column('father_profession', sa.String(length=100), nullable=True),
    sa.Column('brothers_count', sa.Integer(), nullable=True),
    sa.Column('sisters_count', sa.Integer(), nullable=True),
    sa.Column('residence_address', sa.String(length=200), nullable=True),
    sa.Column('residence_city', sa.String(length=100), nullable=True),
    sa.Column('residence_prefecture', sa.String(length=100), nullable=True),
    sa.Column('personal_phone', sa.String(length=20), nullable=True),
    sa.Column('parents_phone', sa.String(length=20), nullable=True),
    sa.Column('education', sa.String(length=200), nullable=True),
    sa.Column('special_skills', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('medical_category', sa.String(length=20), nullable=True),
    sa.Column('amka', sa.String(length=11), nullable=True),
    sa.Column('tax_number', sa.String(length=20), nullable=True),
    sa.Column('iban', sa.String(length=27), nullable=True),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('parent_email', sa.String(length=120), nullable=True),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('military_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soldier_id', sa.Integer(), nullable=False),
    sa.Column('duty_type_id', sa.Integer(), nullable=False),
    sa.Column('duty_date', sa.Date(), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=True),
    sa.Column('position_in_team', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['duty_type_id'], ['duty_type.id'], ),
    sa.ForeignKeyConstraint(['soldier_id'], ['soldier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_time_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty_type_id', sa.Integer(), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['duty_type_id'], ['duty_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['soldier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('soldier_leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soldier_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['soldier_id'], ['soldier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staffing_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('duty_type_id', sa.Integer(), nullable=False),
    sa.Column('required_staff', sa.Integer(), nullable=False),
    sa.Column('available_staff', sa.Integer(), nullable=False),
    sa.Column('shortage', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['duty_type_id'], ['duty_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffing_alert')
    op.drop_table('soldier_leave')
    op.drop_table('equipment')
    op.drop_table('duty_time_slot')
    op.drop_table('duty_assignment')
    op.drop_table('activity_log')
    op.drop_table('user')
    op.drop_table('soldier')
    op.drop_table('duty_type')
    op.drop_table('duty_schedule')
    # ### end Alembic commands ###
